### ISSUE TITLE
Spatial METE and Conlisk models

### ISSUE THREAD

**Issue by dmcglinn** [cmerow/meteR#2]
Hey @ajrominger and @cmerow 

When I was working on a spatial METE DDR project (https://github.com/weecology/mete-spatial) I wrote a lot of code for looking at the spatial species abundance distribution predicted by METE and more generally under the models developed in [Conlisk et al's (2007)](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/06-0122). I'm wondering if you guys would see value in incorporating these functions into your R package. Here are some of the relevant files:

https://github.com/weecology/mete-spatial/blob/master/scripts/spat_analytical_prob_funcs.R

https://github.com/weecology/mete-spatial/blob/master/scripts/heap.c

Erin Conlisk wrote her code in matlab and I translated that into R and C (where necessary). I'm not sure how generally useful these will be for folks and they are a little more general than just METE but maybe this would get these methods greater exposure than my one off project repo will get them. Let me know what you think.

Thanks!

Dan

**Comment by ajrominger** [comment]
hey Dan! this is awesome thanks for sharing.  i think it would be great to incorporate these somewhere. one thought is that, to keep meteR focused on core METE, we could consider adding the Conlisk models to [pika](https://github.com/ajrominger/pika) which will hopefully be a much more broad macroecological package.  I haven't put much time into this lately, but @cmerow kindly wrote this package into a collaboration on a DBI grant, so we might move ahead on it soon.  you all would both be very welcome to help make pika the go-to macroecology package if you all would like!

thanks again for sharing Dan, would be great to keep in touch about this and other chances to collaborate!

**Comment by dmcglinn** [comment]
Sounds good! A general macroecology package for R sounds very cool and like a good home for these functions. I'll start an issue over at `pika`

**Comment by cmerow** [comment]
Agree, sounds good.
